version: 0.0
os: linux
files:
  - source: ./AkkatHttpTest-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/app1/
  - source: ./start_server.sh
    destination: /home/ec2-user/app1/scripts/
  - source: ./stop_server.sh
    destination: /home/ec2-user/app1/scripts/
hooks:
  ApplicationStart:
    - location: ./start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./stop_server.sh
      timeout: 300
      runas: root