version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean install spring-boot:repackage
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mv target/AkkatHttpTest-1.0-SNAPSHOT.jar ./
artifacts:
  files:
    - ./AkkatHttpTest-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes